### ISSUE TITLE
Support combined presets

### ISSUE THREAD

**Issue by alterNERDtive** [alterNERDtive/bindED#15]
> Split up the control binding menu into 4 parts: general, ship, SRV and on-foot - each part can be set to its own preset.

https://forums.frontier.co.uk/threads/elite-dangerous-odyssey-patch-notes.575175/

Again, I do not own Odyssey. So I will need some example files (the presets + whatever file Odyssey saves the combination used in) to be able to even start working on this.

**Comment by tlwalker** [comment]
Here are the two .binds files I use. Custom.4.0.binds is only used on foot. The other is for everything else.
[E:D Odyssey keybinds](https://gist.github.com/tlwalker/3b7cf0fbb1052f1ea7991908ce703559)

**Comment by tlwalker** [comment]
I updated the gist with the StartPreset.start file. I seems to have the binds listed in this order: General Controls, Ship Controls, SRV Controls, On Foot Controls.

**Comment by alterNERDtive** [comment]
Cool, tyvm. What happens when you load into Horizons? Does it take the first in the list? When you change presets in Horizons, does it wipe the combination for Odyssey?

**Comment by tlwalker** [comment]
Opening the Controls option in Horizons and leaving will overwrite this leaving only one line. 
Horizons also defaults to the higher priority default keybind. In my case it was the SaitekX52 keybinds. So when there are multiple line it looks like Horizon can't understand the StartPreset.start file.

**Comment by alterNERDtive** [comment]
> Opening the Controls option in Horizons and leaving will overwrite this leaving only one line.

Come on, now you’re pulling my leg.

Please tell me you’re pulling my leg.

> Horizons also defaults to the higher priority default keybind. In my case it was the SaitekX52 keybinds. So when there are multiple line it looks like Horizon can't understand the StartPreset.start file.

… leg? … pull?

What do you mean by “higher priority” keybind?

**Comment by tlwalker** [comment]
Unfortunately no leg pulling here. I opened the Controls options looked at what it had set in the top right and clicked "cancel" and it overwrote my StartPreset.start file.

By "higher priority default keybind" I mean E:D has a choice of using keyboard and mouse only, keyboard and mouse yaw, generic joystick, SaitekX52 for me. Somewhere in the game it has logic that determined that it should pick the SaitekX52 built-in bindings and not the others.

**Comment by alterNERDtive** [comment]
Ugh. But I guess I don’t have to know which one is picked since I can just read the one the game thinks it wants from the file anyway.

**Comment by alterNERDtive** [comment]
Oh, and more fun!

![image](https://user-images.githubusercontent.com/53827887/118885694-61f86100-b8f8-11eb-94d3-8074e7a69dd1.png)

**Comment by richardbuckle** [comment]
Verified empirically that the 4 lines in `StartPreset.start` are, from the top:
- General
- Ship
- SRV
- On Foot

However if you relaunch in Horizons, it does not understand the 4-line format and reverts to `DefaultContext`. That is horrible.

If you then manually select a preset in Horizons it smashes the 4-line format back to a 1-line format. That is also horrible.

**Comment by tlwalker** [comment]
I submitted the Horizon - Odyssey key bind  interaction as a bug to FDev. This does not seem like expected behavior. [Key Binds Preset Will Reset When you Open Horizons after Odyssey](https://issues.frontierstore.net/issue-detail/31187)

**Comment by DrSchabbs** [comment]
[EDControls-screenshots+csvofcomparison.zip](https://github.com/alterNERDtive/bindED/files/6519522/EDControls-screenshots%2Bcsvofcomparison.zip)

Hi Alt, 

As discussed on discord, screenshots of contents within the menus.
I have also gone ahead and put a side by side csv file of the key names next to each other.

As mentioned in discord, I managed to get bindED working by changing the code on line 290 - changed from:


`           return File.ReadAllText(startFile);`

To

` 
            return File.ReadLines(startFile).First();
`

This only works because I have a single binds file.

**Comment by alterNERDtive** [comment]
Just as a heads up, the result of the incoming fix will most likely be a) you’ll have to use a single preset for all 4 categories and b) you cannot have anything set to “hold” if you want VA to handle it.

And I know better than to promise that I will add support for those in the future :)

**Comment by DrSchabbs** [comment]
the hold thing is a whole other pain in the butt...
I made the below change to my local copy - aka if horizons, grab the first line.
if odyssey, grab second line (ship) - As I mainly use mine for jumping/exploration.... not srv/on foot this works for me.
Did do some additional testing with setting game based presets.

If people are using the inbuilt presets, bindED already throws an error at default presets.
As soon as they make a change to their preset (without creating a new custom file) it just becomes "Custom"
I did notice a file size difference when I set a preset of kb+m in on-foot, applied, then switched to custom from dropdown and applied.
Didn't compare the file file contents as to what was stripped out but custom went from a 61KB file to a 48KB file.... so there was clearly something stripped. I cringed, then replaced my file with a backup for just such an occurance.


Anyways - onto my lazy change.
Was going to compare strings and see how many of the strings were different.

`            if (File.ReadLines(startFile).Count() == 1)
            {
                return File.ReadLines(startFile).ElementAt(0);
            }
            else
            {
                return File.ReadLines(startFile).ElementAt(1);
            }`

**Comment by alterNERDtive** [comment]
> If people are using the inbuilt presets, bindED already throws an error at default presets.
> As soon as they make a change to their preset (without creating a new custom file) it just becomes "Custom"

Yes, that has always been the case (see #12); so far it has never been an issue, people that want to use VA usually also have made at least some changes to their binds ;)

I should add a bit about that to the README though.

**Comment by alterNERDtive** [comment]
> I made the below change to my local copy - aka if horizons, grab the first line.
> if odyssey, grab second line (ship) - As I mainly use mine for jumping/exploration.... not srv/on foot this works for me.

BTW, this is not something I can just assume for everyone. So if you want to keep that behaviour, you’ll have to update/rebase your fork and maintain it for yourself.
