### ISSUE TITLE
Horizons binds files are now versioned as 3.8 instead of 3.0

### ISSUE THREAD

**Issue by alterNERDtive** [alterNERDtive/bindED#16]
2ⁿᵈ hand info, won’t be able to confirm until tomorrow.

That means that in combination with #15 the plugin now breaks for _both_ Odyssey _and_ Horizons.

Yay \o/

**Comment by alterNERDtive** [comment]
So, I took a `4.0` preset, changed it to `3.8`. Loaded into the game, selected the preset. Game loaded it, stripped the Odyssey binds. So far, so good.

Upon changing a bind, the game _wrote a `3.0` file_.

Upon restarting the game, it _read the `3.0` file_.

So I need someone to actually narrow down for me when a 3.8 file appears.

**Comment by UseLessUK** [comment]
I loaded Horizons and reset the controller layout to Default Context and then altered a couple of bindings and the file was saved as `Custom.3.0.binds`

**Comment by alterNERDtive** [comment]
I’m just gonna go ahead and close this until someone actually sees that in the wild. Guess my 2ⁿᵈ hand information was … well, not great.
