### ISSUE TITLE
bindED Unable to find bindings file in Odyssey

### ISSUE THREAD

**Issue by SargeRyong** [alterNERDtive/bindED#17]
Using VA 1.8.7.12, alerNERDtive profiles 4.2.1, bindED 4.0

The first time a command is recognized, bindED looks like it's trying to load the binding values, but fails to do so with the message:

```
ERROR | bindED: No bindings file found for preset 'Custom
Custom
Custom
Custom'.  If this is a default preset, please change anything in Elite's controls options.
```

Thought maybe changing some bindings would poke it into recognizing the file, but it does not.  

The binding files in my bindings directory are:

Custom.3.0.binds
Custom.4.0.binds

The contents of Custom.4.0.binds are available here: https://pastebin.com/YgQtTF7d

StartPreset.start reads

```
Custom
Custom
Custom
Custom
```

(Worked as expected pre-Odyssey update)

**Comment by DrSchabbs** [comment]
Hi Sarge,

Issues 15 and 16 are also relating to this exact issue.
I've just posted a response on #15 
I've explained how I managed to fix this on my version that had the exact same issue, it's not a permanent fix but it does work.

**Comment by SargeRyong** [comment]
> 
> 
> Hi Sarge,
> 
> Issues 15 and 16 are also relating to this exact issue.
> I've just posted a response on #15
> I've explained how I managed to fix this on my version that had the exact same issue, it's not a permanent fix but it does work.

Thanks for the info!  Unfortunately I don't currently have the capability to compile C#, but if I get desperate I'll give it a go.  Glad to know that there is a simple workaround.

**Comment by DrSchabbs** [comment]
Hi Sarge,

I've just forked and thrown up a compiled version, if you get desperate.
NOT the official version, AlterNERDtive does amazing work and will come up with a real solution.
This is just a bandaid fix.

**Comment by SargeRyong** [comment]
Awesome, thanks a bunch!  Looks like its working for me for now.

**Comment by alterNERDtive** [comment]
@SargeRyong as Schabbs has said, see #15 / #16. Also ETA for a fix is hopefully tomorrow.
