### ISSUE TITLE
bindED not working at all

### ISSUE THREAD

**Issue by Darkcyde13** [alterNERDtive/bindED#22]
I've downloaded the latest version of bindED (v4.0), and made a change in the game's controls as instructed, but none of the controls are set in VA at all.  When I check for them, they just say 'Not set'.  Plus, I'm constantly getting an error in the VA log, as per the attached image.

![image](https://user-images.githubusercontent.com/24360725/119261225-6362ab80-bbce-11eb-9bcd-f749601948ce.png)

I assume that the "Custom Custom Custom Custom" are the profiles used for each of the four control types: General, Ship, SRV, and On Foot.  When I change one of these in game to be (for example) Keyboard and Mouse, then one of those 'Custom' entries will change to 'Keyboard and Mouse'.

I've not loaded into Horizons since Odyssey came out, could that be causing this?

I know you don't have Odyssey, so if there is anything I can provide to help with this, just let me know.

**Comment by alterNERDtive** [comment]
See #15 and #16, do please try https://github.com/alterNERDtive/bindED/releases/tag/release%2F4.1 and open an issue if you are still running into problems.
