### ISSUE TITLE
Can't get it.

### ISSUE THREAD

**Issue by Mad-Virus** [alterNERDtive/bindED#27]
Hi,
since over a week now i am trying to get this working. I havent played ED since 2 Years and want to play again,
I've found out about bindED 3.x on a thread at elitedangerous.de. Since then i am looking for answeres to my Questions.
Don't want to say that you have no documentation of your tool but, you explain a lot about how it works, what it do, but for People like me that dont use bindED since the beginning with lousy VA knowledge is the Problem "How to use it".

First of all, i have an old VA-Profile. All of the commands locking something like this:
```
Execute external plugin, 'bindED Plugin v4.1-alterNERDtive'
Press variable key(s) [edFocusRightPanel] and hold for 0,5 seconds and release
Execute command, '(( ED KB Pause ))' (and wait until it completes)
```
Now you say on a Forum 

> Automatic key bind detection. No running a plugin context necessary. 

Nice to know, but what about a example how it has to be now 😕 

Next is, i want to create a de-de Key Layout, I feel like a Pro about that after reading all your informations about how to create one. 🤣  But i also want to use it. 

All Information about that is.

> You can set a text variable in VoiceAttack called bindED.layout# to the layout you want to use. If the variable is not set it will defaut to en-us.

Where exactly do i put that? How exactly does that look like? I have absolut no Idea what that means.
For normal i crate my stuff by trial and error because i have no clue about VA and how to create something cool, sometimes it happens. sometimes not, But my experience with bindED was a chain of No's.

Can you help me please and explain how to use your realy nice Tool now?

Greetings
MadVirus

**Comment by alterNERDtive** [comment]
First of all, have you had a look at [the new docs](https://alternerdtive.github.io/bindED/)? Not very prominently linked yet since they’re brand new.

> I've found out about bindED 3.x on a thread at elitedangerous.de.

Do you have a link?

> All of the commands locking something like this:
> 
> `Execute external plugin, 'bindED Plugin v4.1-alterNERDtive'`

Well that is wrong, and should report an error in the VA log. Even with the very old version made by Gary you would only have to do this _once_ in your startup command.

> `Press variable key(s) [edFocusRightPanel] and hold for 0,5 seconds and release`

That’s correct, assuming you want to go to the right panel. Timing is probably a bit generous.

> `Execute command, '(( ED KB Pause ))' (and wait until it completes)`

No idea what that does, but you probably know the profile better than I do.



>> You can set a text variable in VoiceAttack called `bindED.layout#` to the layout you want to use. If the variable is not set it will defaut to en-us.
> 
> Where exactly do i put that? How exactly does that look like? I have absolut no Idea what that means.

Have a look at the VoiceAttack documentation. You want to have a command that runs on profile loading and that sets that text variable.

**Comment by Mad-Virus** [comment]
Hi and thank's for you answere,

> First of all, have you had a look at [the new docs](https://alternerdtive.github.io/bindED/)? Not very prominently linked yet since they’re brand new.

I've checked that but did not get any idea of the how to.


> Do you have a link?

https://elitedangerous.de/forum/index.php?thread/21150-bind-ed-plugin-f%C3%BCr-voice-attack/


> Well that is wrong, and should report an error in the VA log. Even with the very old version made by Gary you would only have to do this _once_ in your startup command.

Yes it always give an error and reprint the error every time VA is executing a command but i could not figure out what that error wants to say me.

So i'll go delete all this plugin calls, after that i try to find out how to set somthing up in the startup command, and after that I'll Check out the VA Doc to find out how to set that text variable thing for the key layout.

Thanks for pointing me in the right direction.

Greetings
MadVirus

**Comment by alterNERDtive** [comment]
Feel free to re-open this or hop into Discord if you run into any additional problems.

**Comment by alterNERDtive** [comment]
> Yes it always give an error and reprint the error every time VA is executing a command but i could not figure out what that error wants to say me.

It says you can’t give it an empty plugin context (= basically the name of the function the plugin is supposed to run).

> after that i try to find out how to set somthing up in the startup command

That is covered in point 5/6 in the thread you linked …

> and after that I'll Check out the VA Doc to find out how to set that text variable thing for the key layout.

… just use a “set a text variable” action instead of the “execute an external plugin” action.
