### ISSUE TITLE
Persistent configuration

### ISSUE THREAD

**Issue by tbayart** [alterNERDtive/bindED#37]
Hi there,

I'm a french user with European AZERTY keyboard.
To be able to map keys to VoiceAttack, i added a `fr-fr` keyboard layout.

The fact is the layout is not loaded until the `bindED.layout#` command is executed.
What is not very practical is, i have to do that every time i run VoiceAttack.

Could bindED have an optional configuration file where some settings like the default layout can be changed ?

**Comment by alterNERDtive** [comment]
The general idea is to set the layout in your profile’s startup command.

I might want to add that to the documentation somewhere.

**Comment by tbayart** [comment]
Good point about the startup command.
Thanks for the tip.
