### ISSUE TITLE
Some bindings not always working

### ISSUE THREAD

**Issue by Vince1024** [alterNERDtive/bindED#40]
Hi,

I noticed that some bindings are not always working in VA.
For example, 'edShipSpotLightToggle' sometimes works and sometimes not in the same VA command.

I also noticed that many binds are both present in bindED-bindsList.txt AND in bindED-missingBings.txt when executing the 'generate reports' command.

bindED-diagnostics don't show any error.

Is there some plugin logs I could see to understand what's happened or is it a known issue ?

See screenshot of the file compare I did.

Thanks for your good work.
Vincent.

![File Compare](https://user-images.githubusercontent.com/81962401/234535465-5a5a951d-08ef-484c-baa1-2068feb6517e.png)

**Comment by alterNERDtive** [comment]
> I noticed that some bindings are not always working in VA. For example, 'edShipSpotLightToggle' sometimes works and sometimes not in the same VA command.

As long as it doesn’t complain about the variable not being said, bindED is doing its job. Try increasing the time the key is pressed for.

> I also noticed that many binds are both present in bindED-bindsList.txt AND in bindED-missingBings.txt when executing the 'generate reports' command.

That is working as intended. The list shows _all_ binds. It’s basically just a less convoluted way of getting a full list of all binds than having to go through the XML files.

**Comment by Vince1024** [comment]
Hi,
Ok but what should be the difference between bindED-bindsList.txt and bindED-missingBings.txt ?
I though the first should contains all commands that actually have a binded key and the second one to contains commands that does not have one.
Am I wrong ?

**Comment by alterNERDtive** [comment]
The binds list contains all binds Elite has. The missing binds are the ones without a keyboard assignment. The delta is the set of binds that _do_ already have a keyboard assignment.

See https://docs.alternerd.tv/bindED/troubleshooting/#diagnosing-plugin-issues
