### ISSUE TITLE
Bind file name format has changed, no longer recognized

### ISSUE THREAD

**Issue by NemethS70** [alterNERDtive/bindED#42]
Hi,

could you give some detailed example or a screenshot, how to give the ~bindsFile variable and the bindfile name to the plugin?

Thanx a LOT!

Al3x

**Comment by alterNERDtive** [comment]
Just specify the name of the file: https://alternerdtive.github.io/bindED/troubleshooting/#specifying-a-binds-file-to-load

Also you should basically never have to do that, it is auto detected.

**Comment by NemethS70** [comment]
new filenames are 4.1 regex as i saw recognize [34].0
maybe im wrong but when i made a copy with 4.0 it loaded :)
thx anyways and nevermind it was a flash for me im not sure i want to dive back to the game
cheers

**Comment by alterNERDtive** [comment]
So nowadays it saves as e.g. `custom.4.1.binds`?

**Comment by NemethS70** [comment]
yes it does :)

**Comment by alterNERDtive** [comment]
Well I might have the time to patch it tomorrow. If you’re really lucky the workflow to build it on Github still works, as I don’t have a Windows machine at hand to build it locally =p

**Comment by alterNERDtive** [comment]
https://github.com/alterNERDtive/bindED/blob/2ff49dd98adc0955aeaf90b344a346733c9b9e40/bindED.cs#L405 and https://github.com/alterNERDtive/bindED/blob/2ff49dd98adc0955aeaf90b344a346733c9b9e40/bindED.cs#L506

(should™ refactor to have the regexp in _one_ place)

**Comment by alterNERDtive** [comment]
Ftr, `\d` is a thing in .Net regexes.

**Comment by alterNERDtive** [comment]
@NemethS70 can you attach one of those 4.1 binds files so I can make sure I’m not missing any changes?

**Comment by DrymarchonShaun** [comment]
[Custom.4.1 - Copy.binds.txt](https://github.com/alterNERDtive/bindED/files/15087498/Custom.4.1.-.Copy.binds.txt)

Example should be attached *ignore the .txt extension, github wasn't happy with it being .binds

**Comment by alterNERDtive** [comment]
TY!

**Comment by alterNERDtive** [comment]
Reminder to fix https://github.com/alterNERDtive/bindED/blob/2ff49dd98adc0955aeaf90b344a346733c9b9e40/bindED.cs#L518 as well … even though probably nobody™ is playing legacy anyway, just as Frontier intended.
