### ISSUE TITLE
Primary & Secondary bindings

### ISSUE THREAD

**Issue by Catreina** [alterNERDtive/bindED#6]
Allow primary AND secondary keybindings to be used

**Comment by alterNERDtive** [comment]
I’m not sure what you mean. It will already check both.

Then it prefers primary, but it’s a purely arbitrary thing and really doesn’t matter.

**Comment by alterNERDtive** [comment]
Looking through the code I might have introduced a bug that presses _both_ binds if you have a primary and a secondary keyboard bind. Is that what you meant?

**Comment by alterNERDtive** [comment]
Scratch that, the secondary binds check will actually only do anything if there wasn’t anything found in the primary (`if (keys.Count == 0 && …`). Note to self: don’t look at code at 2 AM.

https://github.com/alterNERDtive/bindED/blob/release/bindED.cs#L309

Kepping this as is though until there’s been some feedback :)

**Comment by alterNERDtive** [comment]
Cleared up in discord; for the record, it does check primary first, then secondary if primary doesn’t hold an actual keyboard binding.
