### ISSUE TITLE
Document variable naming

### ISSUE THREAD

**Issue by alterNERDtive** [alterNERDtive/bindED#9]
Document somewhere that it’s just straight up from the binds files with `ed` prepended.

**Comment by ArNeo-VR** [comment]
I've a [Google sheet](https://docs.google.com/spreadsheets/d/1LesTitHgI9L5cXfF-hgUVSKH4joeWj1AUAZWi--_GSI/edit) for the 'variable key-presses' in voice attack, I use it to create commands.
If it's useful, use it as your like.

**Comment by alterNERDtive** [comment]
Thanks, will probably be useful for #10 :)

**Comment by alterNERDtive** [comment]
Fixed for https://alternerdtive.github.io/bindED/ / next release.
